name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make libtbb-dev golang
      - name: Build core and CLI
        run: make
      - name: Run core tests
        run: make test
      - name: Build Go API (cgo)
        run: |
          cd api/go
          SORTBENCH_CGO=1 go build .

