name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make libtbb-dev golang
      - name: Build core and CLI
        run: make
      - name: Run core tests
        run: make test
      - name: Go unit tests (shell-out mode)
        working-directory: api/go
        env:
          SORTBENCH_BIN: ../../sortbench
        run: |
          go mod tidy
          go test -race -v
      - name: Build Go API (cgo)
        working-directory: api/go
        env:
          CGO_ENABLED: 1
        run: |
          SORTBENCH_CGO=1 go build .
